# Generated by Django 3.0.3 on 2020-03-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_habitacion_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitacion',
            old_name='numeroCamas',
            new_name='numeroCamasDobles',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='numeroCamasSencillas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
