# Generated by Django 3.0.3 on 2020-03-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20200320_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='numeroMaximoAdultos',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitacion',
            name='numeroMaximoNiños',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='numeroAdultos',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='numeroNiños',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
